## ui-builder
FROM node:12.6.0-buster as ui-builder
WORKDIR /app

## environment variables setup
COPY .env .
RUN /bin/bash -c "source /app/.env"

ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build

## production 
FROM nginx:1.13.8 as production-stage
COPY --from=ui-builder /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]




