## ui-builder
FROM node:12 as ui-builder
WORKDIR /app

## environment variables setup: Not required here, can be passed during docker run
#COPY .env .
#RUN /bin/bash -c "source /app/.env"

ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install --silent
RUN npm install -g @vue/cli
RUN rm -f .env*
CMD ["npm", "run", "serve"]





