## ui-builder
FROM node:12 as ui-builder
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install --silent
ADD . /app
RUN rm -f .env*

CMD ["npm", "run", "serve"]





